# https://python-poetry.org/docs/pyproject/

# PROJECT

[tool.poetry]
name = "cookiecutter-ds"
version = "2.3.1"
description = "Cookiecutter template for DS, ML, or Python library development."
repository = "https://github.com/jmquintana79/cookiecutter-ds"
documentation = "https://github.com/jmquintana79/cookiecutter-ds/"
authors = ["Juan Quintana <juan.armaguedon@icloud.com>"]
readme = "README.md"
license = "MIT License"

# DEPENDENCIES

[tool.poetry.dependencies]
python =  ">=3.09,<3.10"
setuptools = "^71.1.0"
python-dotenv = "*"
invoke = "^2.2.0"
cookiecutter = "^2.6.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.1"
ruff = "^0.5.0"
commitizen = "^3.27.0"
pdoc = "^14.5.1"
interrogate = "^1.7.0"
ipykernel = "^6.29.4"
nbformat = "^5.10.4"

[tool.poetry.group.tests.dependencies]
pytest = "^8.2.2"


# CONFIGURATIONS

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true

[tool.mypy]
pretty = true
strict = true
python_version = "3.09"
check_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--verbosity=2"
pythonpath = ["src"]

[tool.ruff]
fix = true
indent-width = 4
line-length = 100
target-version = "py311"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D100", "D103"]

# SYSTEMS

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"